### PR TITLE
Random little things

### PR DESCRIPTION
**Pull request by Eahlstan**
SAAScancomplete was missing in the JumpScanEssentialEvents section but was in the scan sections. This led to wrong value calculations when selecting old systems.

Added ScanOrganic to all scan sections to make the new Scan Organic panel display past scans.

### CODE REVIEW

**Comment by Eahlstan** [comment]
Deleted duplicate of "Engineered FSD v1" and added "Engineered Surface Scanner v1".

**Comment by Eahlstan** [comment]
https://github.com/EDDiscovery/EDDiscovery/issues/3216

**Comment by robbyxp1** [comment]
Hmm estimatedvalues.cs diff is showing addition to the OrganicEstimatedValues, when it should not, its already in master..

I may have to cherry pick these changes off later.

**Comment by Eahlstan** [comment]
> Hmm estimatedvalues.cs diff is showing addition to the OrganicEstimatedValues, when it should not, its already in master..
> 
> I may have to cherry pick these changes off later.

I totally think that this PR will get closed, see it as a reminder of things we have to talk about before the next release ;)

**Comment by Eahlstan** [comment]
As there seems no way to get those damned bubble bodies right this change puts us in the same range as EDSM on those bodies (plus or minus a bit due to base value shenanigans).
Note: the estimated values panel needs adaption, remind me before release.

**Comment by robbyxp1** [comment]
Some manual merges of these changes. closing as out of date now.

**Pull request closed without merging**
